services:
  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/power-control
    init: true
    volumes:
      - ./:/home/python/power-control
    working_dir: /home/python/power-control
